// Generates lib/core/theme/tokens.dart from the brand package colour tokens.
//
//   dart run tool/generate_tokens.dart          # (re)write the Dart file
//   dart run tool/generate_tokens.dart --check  # exit 1 if it is out of date
//
// Run from apps/mobile. test/design/tokens_test.dart runs the same check.

import 'dart:convert';
import 'dart:io';

const String tokensSourcePath =
    '../../assets/brand/04_ui_color_tokens/bafo_colors.json';
const String tokensOutputPath = 'lib/core/theme/tokens.dart';

void main(List<String> args) {
  final json = jsonDecode(
    File(tokensSourcePath).readAsStringSync(),
  ) as Map<String, dynamic>;
  final rendered = renderTokens(json);
  final output = File(tokensOutputPath);

  if (args.contains('--check')) {
    final current = output.existsSync() ? output.readAsStringSync() : '';
    if (current != rendered) {
      stderr.writeln(
        '$tokensOutputPath is out of date. Run: dart run tool/generate_tokens.dart',
      );
      exitCode = 1;
    }
    return;
  }
  output.writeAsStringSync(rendered);
  stdout.writeln('Wrote $tokensOutputPath');
}

/// Renders the Dart source for [json] (the shape of `bafo_colors.json`).
String renderTokens(Map<String, dynamic> json) {
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/generate_tokens.dart from')
    ..writeln(
      '// assets/brand/04_ui_color_tokens/bafo_colors.json. Do not edit by hand.',
    )
    ..writeln()
    ..writeln("import 'dart:ui' show Color;")
    ..writeln()
    ..writeln(
      '/// Official BAFO colour tokens (brand package). Roles that the package does',
    )
    ..writeln(
      '/// not define (dark-mode brand colours, AA text variants) live in',
    )
    ..writeln('/// `derived_colors.dart`.')
    ..writeln('abstract final class BafoTokens {');

  // Mirrors `dart format`: a documented member after another member gets a blank line.
  var afterDeclaration = false;
  void color(String name, String hex, [String? doc]) {
    if (doc != null) {
      if (afterDeclaration) out.writeln();
      out.writeln('  /// $doc');
    }
    out.writeln('  static const Color $name = Color(${_argb(hex)});');
    afterDeclaration = true;
  }

  final brand = json['brand'] as Map<String, dynamic>;
  out.writeln('  // Brand');
  afterDeclaration = false;
  for (final entry in brand.entries) {
    final token = entry.value as Map<String, dynamic>;
    color(
      'brand${_pascal(entry.key)}',
      token['value'] as String,
      token['usage'] as String?,
    );
  }

  final gray = json['gray'] as Map<String, dynamic>;
  out
    ..writeln()
    ..writeln('  // Gray scale');
  afterDeclaration = false;
  for (final entry in gray.entries) {
    color('gray${entry.key}', entry.value as String);
  }

  final semantic = json['semantic'] as Map<String, dynamic>;
  out
    ..writeln()
    ..writeln('  // Semantic');
  afterDeclaration = false;
  for (final entry in semantic.entries) {
    final token = entry.value as Map<String, dynamic>;
    color(entry.key, token['value'] as String);
    color('${entry.key}Background', token['background'] as String);
  }

  final surface = json['surface'] as Map<String, dynamic>;
  for (final mode in surface.entries) {
    out
      ..writeln()
      ..writeln('  // Surface: ${mode.key}');
    afterDeclaration = false;
    for (final entry in (mode.value as Map<String, dynamic>).entries) {
      color('${mode.key}${_pascal(entry.key)}', entry.value as String);
    }
  }

  out.writeln('}');
  return out.toString();
}

String _pascal(String key) => key[0].toUpperCase() + key.substring(1);

String _argb(String hex) {
  final digits = hex.replaceFirst('#', '').toUpperCase();
  if (digits.length != 6) {
    throw FormatException('Expected #RRGGBB, got $hex');
  }
  return '0xFF$digits';
}
