// GENERATED by tool/generate_tokens.dart from
// assets/brand/04_ui_color_tokens/bafo_colors.json. Do not edit by hand.

import 'dart:ui' show Color;

/// Official BAFO colour tokens (brand package). Roles that the package does
/// not define (dark-mode brand colours, AA text variants) live in
/// `derived_colors.dart`.
abstract final class BafoTokens {
  // Brand
  /// primary brand color, dominant — buttons, links, active states
  static const Color brandGreen = Color(0xFF0E9F6E);

  /// hover/active state for primary green
  static const Color brandGreenDark = Color(0xFF0B7A55);

  /// tinted backgrounds, badges, success surfaces
  static const Color brandGreenLight = Color(0xFFE6F7F1);

  /// accent — controlled use only: icon mark, destructive actions
  static const Color brandRed = Color(0xFFB3261E);

  /// hover/active state for destructive actions
  static const Color brandRedDark = Color(0xFF8C1E17);

  /// error background tint
  static const Color brandRedLight = Color(0xFFFBEAE9);

  /// wordmark, primary text, dark surfaces
  static const Color brandCharcoal = Color(0xFF1C1F26);

  // Gray scale
  static const Color gray50 = Color(0xFFF9FAFA);
  static const Color gray100 = Color(0xFFF3F4F5);
  static const Color gray200 = Color(0xFFE5E7EB);
  static const Color gray300 = Color(0xFFD1D5DB);
  static const Color gray400 = Color(0xFF9AA0A6);
  static const Color gray500 = Color(0xFF6B7280);
  static const Color gray600 = Color(0xFF4B5563);
  static const Color gray700 = Color(0xFF374151);
  static const Color gray800 = Color(0xFF1F2937);
  static const Color gray900 = Color(0xFF1C1F26);

  // Semantic
  static const Color success = Color(0xFF0E9F6E);
  static const Color successBackground = Color(0xFFE6F7F1);
  static const Color error = Color(0xFFB3261E);
  static const Color errorBackground = Color(0xFFFBEAE9);
  static const Color warning = Color(0xFFB7791F);
  static const Color warningBackground = Color(0xFFFEF3E2);
  static const Color info = Color(0xFF2563EB);
  static const Color infoBackground = Color(0xFFEAF1FE);

  // Surface: light
  static const Color lightBgPage = Color(0xFFFFFFFF);
  static const Color lightBgSurface = Color(0xFFF9FAFA);
  static const Color lightBgSurfaceAlt = Color(0xFFF3F4F5);
  static const Color lightBorderDefault = Color(0xFFE5E7EB);
  static const Color lightTextPrimary = Color(0xFF1C1F26);
  static const Color lightTextSecondary = Color(0xFF6B7280);
  static const Color lightTextOnBrand = Color(0xFFFFFFFF);

  // Surface: dark
  static const Color darkBgPage = Color(0xFF14161B);
  static const Color darkBgSurface = Color(0xFF1C1F26);
  static const Color darkBgSurfaceAlt = Color(0xFF262A33);
  static const Color darkBorderDefault = Color(0xFF333844);
  static const Color darkTextPrimary = Color(0xFFF3F4F5);
  static const Color darkTextSecondary = Color(0xFF9AA0A6);
}
